module.exports = Object.freeze({
    V: {EL:0, ELLA:1, ELLOS:2, ELLAS:3, X:4, XS:5},
    T: {VERBO:1, DETERMINANTE:2, NOMBRE:3, ADVERBIO:4, CONJUNCION:5, INTERJECCION:6, PREPOSICION:7, ADJETIVO:8, PRONOMBRE:9 }
});